#!/usr/bin/env ruby
#^syntax detection
site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'dotdeb', :git => 'git://github.com/homemade/chef-dotdeb.git'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'openssl'
cookbook 'php'
cookbook 'postfix'
cookbook 'app', :path => './site-cookbooks/app'